package com.profitz.app.util;

import android.annotation.SuppressLint;
import android.database.Cursor;

import com.profitz.app.data.model.Promo;
import com.profitz.app.data.source.local.provider.MovieContract.MovieEntry;

import java.util.ArrayList;
import java.util.List;

public class RepositoryUtils {

    public static List<Promo> toMoviesList(Cursor moviesCursor) {
        ArrayList<Promo> promoList = new ArrayList<>();
        for (moviesCursor.moveToFirst(); !moviesCursor.isAfterLast(); moviesCursor.moveToNext()) {
            @SuppressLint("Range") Promo promo = new Promo(
                    moviesCursor.getInt(moviesCursor.getColumnIndex(MovieEntry.COLUMN_VOTE_AVERAGE)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_DIFFICULT)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_SHORT_DESC)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_PRICE)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_PRICE_TYPE)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_HOW_LONG)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_TUTORIAL)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP1)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP1_1)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP1_2)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP1_3)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP1_4)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP1_5)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP1_6)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP1_7)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP2)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP2_1)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP2_2)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP2_3)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP2_4)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP2_5)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP2_6)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP2_7)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP3)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP3_1)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP3_2)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP3_3)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP3_4)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP3_5)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP3_6)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP3_7)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP4)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP4_1)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP4_2)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP4_3)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP4_4)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP4_5)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP4_6)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP4_7)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP5)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP5_1)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP5_2)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP5_3)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP5_4)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP5_5)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP5_6)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP5_7)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP6)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP6_1)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP6_2)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP6_3)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP6_4)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP6_5)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP6_6)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP6_7)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP7)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP7_1)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP7_2)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP7_3)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP7_4)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP7_5)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP7_6)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEP7_7)),
                    moviesCursor.getString( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEPX)),
                    moviesCursor.getInt( moviesCursor.getColumnIndex( MovieEntry.COLUMN_STEPS)),
                    moviesCursor.getInt(moviesCursor.getColumnIndex(MovieEntry.COLUMN_ID)),
                    (moviesCursor.getInt(moviesCursor.getColumnIndex(MovieEntry.COLUMN_VIDEO)) != 0),
                    moviesCursor.getFloat(moviesCursor.getColumnIndex(MovieEntry.COLUMN_VOTE_AVERAGE)),
                    moviesCursor.getString(moviesCursor.getColumnIndex(MovieEntry.COLUMN_TITLE)),
                    moviesCursor.getInt(moviesCursor.getColumnIndex(MovieEntry.COLUMN_POPULARITY)),
                    moviesCursor.getInt(moviesCursor.getColumnIndex(MovieEntry.COLUMN_XP)),
                    moviesCursor.getInt(moviesCursor.getColumnIndex(MovieEntry.COLUMN_DONES)),
                    moviesCursor.getString(moviesCursor.getColumnIndex(MovieEntry.COLUMN_PROMO_TYPE)),
                    moviesCursor.getString(moviesCursor.getColumnIndex(MovieEntry.COLUMN_POSTER_PATH)),
                    moviesCursor.getString(moviesCursor.getColumnIndex(MovieEntry.COLUMN_ORIGINAL_LANGUAGE)),
                    moviesCursor.getString(moviesCursor.getColumnIndex(MovieEntry.COLUMN_ORIGINAL_TITLE)),
                    moviesCursor.getString(moviesCursor.getColumnIndex(MovieEntry.COLUMN_BACKDROP_PATH)),
                    moviesCursor.getInt(moviesCursor.getColumnIndex(MovieEntry.COLUMN_LIKES)),
                    moviesCursor.getInt(moviesCursor.getColumnIndex(MovieEntry.COLUMN_COMMENTS)),
                    moviesCursor.getInt(moviesCursor.getColumnIndex(MovieEntry.COLUMN_REVIEWS)),
                    (moviesCursor.getInt(moviesCursor.getColumnIndex(MovieEntry.COLUMN_ADULT)) != 0),
                    moviesCursor.getString(moviesCursor.getColumnIndex(MovieEntry.COLUMN_OVERVIEW)),
                    moviesCursor.getString(moviesCursor.getColumnIndex(MovieEntry.COLUMN_INSTRUCTION_TYPE)),
                    moviesCursor.getString(moviesCursor.getColumnIndex(MovieEntry.COLUMN_PROMO_RULES_URL)),
                    moviesCursor.getString(moviesCursor.getColumnIndex(MovieEntry.COLUMN_RELEASE_DATE)),
                    true
            );
            promoList.add(promo);
        }
        return promoList;
    }

    @SuppressLint("Range")
    public static Promo toMovie(Cursor movieCursor) {
        if (movieCursor.getCount() == 0) {
            return new Promo(false);
        }

        movieCursor.moveToFirst();
        return new Promo(
            movieCursor.getInt(movieCursor.getColumnIndex(MovieEntry.COLUMN_VOTE_AVERAGE)),
            movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_DIFFICULT)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_SHORT_DESC)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_PRICE)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_PRICE_TYPE)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_HOW_LONG)),
            movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_TUTORIAL)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP1)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP1_1)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP1_2)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP1_3)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP1_4)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP1_5)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP1_6)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP1_7)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP2)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP2_1)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP2_2)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP2_3)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP2_4)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP2_5)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP2_6)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP2_7)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP3)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP3_1)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP3_2)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP3_3)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP3_4)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP3_5)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP3_6)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP3_7)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP4)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP4_1)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP4_2)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP4_3)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP4_4)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP4_5)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP4_6)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP4_7)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP5)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP5_1)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP5_2)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP5_3)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP5_4)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP5_5)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP5_6)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP5_7)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP6)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP6_1)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP6_2)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP6_3)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP6_4)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP6_5)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP6_6)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP1_7)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP7)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP7_1)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP7_2)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP7_3)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP7_4)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP7_5)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP7_6)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEP7_7)),
                movieCursor.getString( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEPX)),
                movieCursor.getInt( movieCursor.getColumnIndex(MovieEntry.COLUMN_STEPS)),
                movieCursor.getInt(movieCursor.getColumnIndex(MovieEntry.COLUMN_ID)),
            (movieCursor.getInt(movieCursor.getColumnIndex(MovieEntry.COLUMN_VIDEO)) != 0),
            movieCursor.getFloat(movieCursor.getColumnIndex(MovieEntry.COLUMN_VOTE_AVERAGE)),
            movieCursor.getString(movieCursor.getColumnIndex(MovieEntry.COLUMN_TITLE)),
            movieCursor.getInt(movieCursor.getColumnIndex(MovieEntry.COLUMN_POPULARITY)),
                movieCursor.getInt(movieCursor.getColumnIndex(MovieEntry.COLUMN_XP)),
                movieCursor.getInt(movieCursor.getColumnIndex(MovieEntry.COLUMN_DONES)),
                movieCursor.getString(movieCursor.getColumnIndex(MovieEntry.COLUMN_PROMO_TYPE)),
                        movieCursor.getString(movieCursor.getColumnIndex(MovieEntry.COLUMN_POSTER_PATH)),
            movieCursor.getString(movieCursor.getColumnIndex(MovieEntry.COLUMN_ORIGINAL_LANGUAGE)),
            movieCursor.getString(movieCursor.getColumnIndex(MovieEntry.COLUMN_ORIGINAL_TITLE)),
            movieCursor.getString(movieCursor.getColumnIndex(MovieEntry.COLUMN_BACKDROP_PATH)),
                movieCursor.getInt(movieCursor.getColumnIndex(MovieEntry.COLUMN_LIKES)),
                movieCursor.getInt(movieCursor.getColumnIndex(MovieEntry.COLUMN_COMMENTS)),
                movieCursor.getInt(movieCursor.getColumnIndex(MovieEntry.COLUMN_REVIEWS)),
            (movieCursor.getInt(movieCursor.getColumnIndex(MovieEntry.COLUMN_ADULT)) != 0),
            movieCursor.getString(movieCursor.getColumnIndex(MovieEntry.COLUMN_OVERVIEW)),
                movieCursor.getString(movieCursor.getColumnIndex(MovieEntry.COLUMN_INSTRUCTION_TYPE)),
                movieCursor.getString(movieCursor.getColumnIndex(MovieEntry.COLUMN_PROMO_RULES_URL)),
            movieCursor.getString(movieCursor.getColumnIndex(MovieEntry.COLUMN_RELEASE_DATE)),
            true
            );
    }
}
